name: Jdk

on:
  push:
    paths:
      - '.github/workflows/jdk.yml'

jobs:
  jdk-16-ea:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://download.java.net/java/early_access/jdk16/13/GPL/openjdk-16-ea+13_linux-x64_bin.tar.gz --output-document jdk.tar.gz
      - uses: actions/setup-java@v2
        with:
          java-version: '16-ea'
          jdkFile: jdk.tar.gz
      - run: java -version
  jdk-15-ea:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://download.java.net/java/early_access/jdk15/1/GPL/openjdk-15-ea+1_linux-x64_bin.tar.gz --output-document jdk.tar.gz
      - uses: actions/setup-java@v2
        with:
          java-version: '15-ea'
          jdkFile: jdk.tar.gz
      - run: java -version
  jdk-14:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz --output-document jdk.tar.gz
      - uses: actions/setup-java@v2
        with:
          java-version: '14.0.2'
          jdkFile: jdk.tar.gz
      - run: java -version
  jdk-14-ea:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download latest-and-greatest JDK 14-ea'
        run: |
          DOCKERFILE=${HOME}/jdk-14.dockerfile
          wget https://github.com/docker-library/openjdk/raw/master/14/jdk/oraclelinux8/Dockerfile --output-document ${DOCKERFILE}
          JAVA_URL=$(cat ${DOCKERFILE} | sed -n 's/ENV JAVA_HOME //p')
          JAVA_VERSION=$(cat ${DOCKERFILE} | sed -n 's/ENV JAVA_VERSION //p')
          wget --directory-prefix ${HOME} ${JAVA_URL}
          echo ::set-env name=JAVA_VERSION::${JAVA_VERSION}
          echo ::set-env name=JDK_FILE::"${HOME}/$(basename ${JAVA_URL})"
      - uses: actions/setup-java@v2
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          jdkFile: "${{ env.JDK_FILE }}"
      - run: java -version
